plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coffeeonelove.iretail.aoahost'
    compileSdk 35

    defaultConfig {
        applicationId 'com.coffeeonelove.iretail.aoahost'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '0.4.0-payment-over-aoa'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
