plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coffeeonelove.iretail.kozenrecovery'
    compileSdk 35

    defaultConfig {
        applicationId 'com.coffeeonelove.iretail.kozenrecovery'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.1.1-read-only-recovery-permission-fix'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
