plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coffeeonelove.iretail.kozenbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.coffeeonelove.iretail.kozenbridge'
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName '0.5.7-sbp-qr-source-probe'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
