plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coffeeonelove.iretail.kozenbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.coffeeonelove.iretail.kozenbridge'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '0.4.1-card-prompt'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
