plugins {
    id 'com.android.application'
}

android {
    namespace 'com.coffeeonelove.iretail.aoarecovery'
    compileSdk 35

    defaultConfig {
        applicationId 'com.coffeeonelove.iretail.aoarecovery'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0-read-only-transaction-recovery'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
